version: '3.8'

services:
  erpnext:
    volumes:
      - ./apps/erpnext:/home/frappe/frappe-bench/apps/erpnext

  wordpress:
    volumes:
      - ./apps/wordpress/wp-content:/var/www/html/wp-content

  mattermost:
    volumes:
      - ./apps/mattermost/config:/mattermost/config
