name: 'Terraform CI/CD'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Google Auth'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.WIF_POOL_ID }}/providers/${{ secrets.WIF_PROVIDER_ID }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - name: 'Terraform Init'
        run: terraform init
        working-directory: ./infrastructure/terraform

      - name: 'Terraform Plan'
        id: 'plan'
        run: terraform plan -no-color -out=tfplan
        working-directory: ./infrastructure/terraform

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve tfplan
        working-directory: ./infrastructure/terraform

      - name: 'Setup Docker'
        uses: docker-practice/actions-setup-docker@master

      - name: 'Compile ERPNext Assets'
        run: |
          docker-compose -f infrastructure/docker/docker-compose.yml run --rm erpnext bench build
